import { useState } from "react";

const metrics = ["總人口", "扶老比", "出生率", "自然增加率", "年出生", "年死亡"];
export function CreateForms({ years, api, refresh }) {
  const [existingStatus, setExistingStatus] = useState(""), [uploadStatus, setUploadStatus] = useState(""), [existingType, setExistingType] = useState("bar"), [uploadType, setUploadType] = useState("bar");
  const sortedYears = [...years].sort((a, b) => Number(b) - Number(a));
  const submitExisting = async (event) => { event.preventDefault(); const form = event.currentTarget, data = Object.fromEntries(new FormData(form)); data.year = Number(data.year); data.data_type = "indicators"; setExistingStatus("正在建立…"); try { await api.fromData(data); form.reset(); setExistingStatus("已建立共享圖層。"); await refresh(); } catch (error) { setExistingStatus(`建立失敗：${error.message}`); } };
  const submitUpload = async (event) => { event.preventDefault(); const form = event.currentTarget; setUploadStatus("正在上傳並驗證…"); try { await api.upload(new FormData(form)); form.reset(); setUploadStatus("已新增共享圖層。"); await refresh(); } catch (error) { setUploadStatus(`上傳失敗：${error.message}`); } };
  return <>
    <details className="custom-layer-form" open><summary>使用現有資料</summary><form className="map-workspace-form" onSubmit={submitExisting}>
      <label className="field">圖層名稱<input name="name" required maxLength="100"/></label><label className="field">年份<select name="year" required>{sortedYears.map((year) => <option key={year}>{year}</option>)}</select></label><label className="field">指標<select name="metric">{metrics.map((metric) => <option key={metric}>{metric}</option>)}</select></label><label className="field">性別<select name="gender"><option>全部</option><option>男</option><option>女</option></select></label><label className="field">圖層類型<select name="chart_type" value={existingType} onChange={(event) => setExistingType(event.target.value)}><option value="bar">長條圖</option><option value="pie">圓餅圖</option><option value="donut">甜甜圈圖</option><option value="choropleth">面量圖</option></select></label>{existingType === "choropleth" && <p className="hint form-wide">面量圖使用單一年度指標，並以五級等距色階呈現。</p>}<button disabled={!years.length}>建立共享圖層</button>
    </form><p className="hint form-status" role="status">{existingStatus}</p></details>
    <details className="custom-layer-form"><summary>上傳 CSV</summary><p className="hint">CSV 必須有「里」欄位；面量圖只能再有一個數值欄。</p><form className="map-workspace-form" onSubmit={submitUpload}><label className="field">圖層名稱<input name="name" required maxLength="100"/></label><label className="field">圖層類型<select name="chart_type" value={uploadType} onChange={(event) => setUploadType(event.target.value)}><option value="bar">長條圖</option><option value="pie">圓餅圖</option><option value="donut">甜甜圈圖</option><option value="choropleth">面量圖</option></select></label><label className="field">CSV 檔案<input name="file" type="file" accept=".csv,text/csv" required/></label><button>上傳圖層</button></form><p className="hint form-status" role="status">{uploadStatus}</p></details>
  </>;
}
